// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Gestion_Tickets.Data;

#nullable disable

namespace Sistema_Gestion_Tickets.Migrations
{
    [DbContext(typeof(SAEContext))]
    [Migration("20250313205331_AddAdminAndEstacionamientoTable")]
    partial class AddAdminAndEstacionamientoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Gestion_Tickets.Models.Administrador", b =>
                {
                    b.Property<int>("IDAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDAdministrador"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDAdministrador");

                    b.ToTable("Administrador");
                });

            modelBuilder.Entity("Sistema_Gestion_Tickets.Models.Estacionamiento", b =>
                {
                    b.Property<int>("IDEstacionamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEstacionamiento"));

                    b.Property<int>("CapacidadTotal")
                        .HasColumnType("int");

                    b.Property<int>("Ocupados")
                        .HasColumnType("int");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("IDEstacionamiento");

                    b.ToTable("Estacionamiento");
                });

            modelBuilder.Entity("Sistema_Gestion_Tickets.Models.Ticket", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo");

                    b.ToTable("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
